//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDExplorer.Pantallas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfiguracionFrm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfiguracionFrm() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDExplorer.Pantallas.ConfiguracionFrm", typeof(ConfiguracionFrm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=154,Y=34}.
        /// </summary>
        public static System.Drawing.Point btn_TestVol_Location {
            get {
                object obj = ResourceManager.GetObject("btn_TestVol.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding btn_TestVol_Margin {
            get {
                object obj = ResourceManager.GetObject("btn_TestVol.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=64, Height=28}.
        /// </summary>
        public static System.Drawing.Size btn_TestVol_Size {
            get {
                object obj = ResourceManager.GetObject("btn_TestVol.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 1.
        /// </summary>
        public static int btn_TestVol_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btn_TestVol.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Probar.
        /// </summary>
        public static string btn_TestVol_Text {
            get {
                return ResourceManager.GetString("btn_TestVol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=165,Y=30}.
        /// </summary>
        public static System.Drawing.Point button1_Location {
            get {
                object obj = ResourceManager.GetObject("button1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding button1_Margin {
            get {
                object obj = ResourceManager.GetObject("button1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=64, Height=28}.
        /// </summary>
        public static System.Drawing.Size button1_Size {
            get {
                object obj = ResourceManager.GetObject("button1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 1.
        /// </summary>
        public static int button1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Probar.
        /// </summary>
        public static string button1_Text {
            get {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=464,Y=52}.
        /// </summary>
        public static System.Drawing.Point button2_Location {
            get {
                object obj = ResourceManager.GetObject("button2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding button2_Margin {
            get {
                object obj = ResourceManager.GetObject("button2.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=64, Height=28}.
        /// </summary>
        public static System.Drawing.Size button2_Size {
            get {
                object obj = ResourceManager.GetObject("button2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 23.
        /// </summary>
        public static int button2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mover.
        /// </summary>
        public static string button2_Text {
            get {
                return ResourceManager.GetString("button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.AnchorStyles similar a Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles button3_Anchor {
            get {
                object obj = ResourceManager.GetObject("button3.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Font similar a [Font: Name=Segoe UI, Size=8,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font button3_Font {
            get {
                object obj = ResourceManager.GetObject("button3.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=552,Y=430}.
        /// </summary>
        public static System.Drawing.Point button3_Location {
            get {
                object obj = ResourceManager.GetObject("button3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=2,Right=3,Bottom=2}.
        /// </summary>
        public static System.Windows.Forms.Padding button3_Margin {
            get {
                object obj = ResourceManager.GetObject("button3.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=88, Height=28}.
        /// </summary>
        public static System.Drawing.Size button3_Size {
            get {
                object obj = ResourceManager.GetObject("button3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 27.
        /// </summary>
        public static int button3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        public static string button3_Text {
            get {
                return ResourceManager.GetString("button3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=464,Y=107}.
        /// </summary>
        public static System.Drawing.Point button4_Location {
            get {
                object obj = ResourceManager.GetObject("button4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding button4_Margin {
            get {
                object obj = ResourceManager.GetObject("button4.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=64, Height=28}.
        /// </summary>
        public static System.Drawing.Size button4_Size {
            get {
                object obj = ResourceManager.GetObject("button4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 25.
        /// </summary>
        public static int button4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thyead.
        /// </summary>
        public static string button4_Text {
            get {
                return ResourceManager.GetString("button4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=464,Y=171}.
        /// </summary>
        public static System.Drawing.Point button5_Location {
            get {
                object obj = ResourceManager.GetObject("button5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding button5_Margin {
            get {
                object obj = ResourceManager.GetObject("button5.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=64, Height=28}.
        /// </summary>
        public static System.Drawing.Size button5_Size {
            get {
                object obj = ResourceManager.GetObject("button5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 26.
        /// </summary>
        public static int button5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string button5_Text {
            get {
                return ResourceManager.GetString("button5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.AnchorStyles similar a Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonAceptar_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonAceptar.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Font similar a [Font: Name=Segoe UI, Size=8,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font buttonAceptar_Font {
            get {
                object obj = ResourceManager.GetObject("buttonAceptar.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=655,Y=430}.
        /// </summary>
        public static System.Drawing.Point buttonAceptar_Location {
            get {
                object obj = ResourceManager.GetObject("buttonAceptar.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=2,Right=3,Bottom=2}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonAceptar_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonAceptar.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=88, Height=28}.
        /// </summary>
        public static System.Drawing.Size buttonAceptar_Size {
            get {
                object obj = ResourceManager.GetObject("buttonAceptar.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 25.
        /// </summary>
        public static int buttonAceptar_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonAceptar.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string buttonAceptar_Text {
            get {
                return ResourceManager.GetString("buttonAceptar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.AnchorStyles similar a Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonCancelar_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonCancelar.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Font similar a [Font: Name=Segoe UI, Size=8,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font buttonCancelar_Font {
            get {
                object obj = ResourceManager.GetObject("buttonCancelar.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=760,Y=430}.
        /// </summary>
        public static System.Drawing.Point buttonCancelar_Location {
            get {
                object obj = ResourceManager.GetObject("buttonCancelar.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=2,Right=3,Bottom=2}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonCancelar_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonCancelar.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=88, Height=28}.
        /// </summary>
        public static System.Drawing.Size buttonCancelar_Size {
            get {
                object obj = ResourceManager.GetObject("buttonCancelar.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 26.
        /// </summary>
        public static int buttonCancelar_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonCancelar.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string buttonCancelar_Text {
            get {
                return ResourceManager.GetString("buttonCancelar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=90,Y=227}.
        /// </summary>
        public static System.Drawing.Point cbx_idioma_Location {
            get {
                object obj = ResourceManager.GetObject("cbx_idioma.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=186, Height=24}.
        /// </summary>
        public static System.Drawing.Size cbx_idioma_Size {
            get {
                object obj = ResourceManager.GetObject("cbx_idioma.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 12.
        /// </summary>
        public static int cbx_idioma_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbx_idioma.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool cbx_VeryInteresting_AutoSize {
            get {
                object obj = ResourceManager.GetObject("cbx_VeryInteresting.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=34,Y=57}.
        /// </summary>
        public static System.Drawing.Point cbx_VeryInteresting_Location {
            get {
                object obj = ResourceManager.GetObject("cbx_VeryInteresting.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding cbx_VeryInteresting_Margin {
            get {
                object obj = ResourceManager.GetObject("cbx_VeryInteresting.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=197, Height=21}.
        /// </summary>
        public static System.Drawing.Size cbx_VeryInteresting_Size {
            get {
                object obj = ResourceManager.GetObject("cbx_VeryInteresting.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 15.
        /// </summary>
        public static int cbx_VeryInteresting_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbx_VeryInteresting.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificar Criterios Multiples.
        /// </summary>
        public static string cbx_VeryInteresting_Text {
            get {
                return ResourceManager.GetString("cbx_VeryInteresting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool cbxBeta_AutoSize {
            get {
                object obj = ResourceManager.GetObject("cbxBeta.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=8,Y=28}.
        /// </summary>
        public static System.Drawing.Point cbxBeta_Location {
            get {
                object obj = ResourceManager.GetObject("cbxBeta.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=2,Right=3,Bottom=2}.
        /// </summary>
        public static System.Windows.Forms.Padding cbxBeta_Margin {
            get {
                object obj = ResourceManager.GetObject("cbxBeta.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=143, Height=21}.
        /// </summary>
        public static System.Drawing.Size cbxBeta_Size {
            get {
                object obj = ResourceManager.GetObject("cbxBeta.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 2.
        /// </summary>
        public static int cbxBeta_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbxBeta.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leer Journal Beta.
        /// </summary>
        public static string cbxBeta_Text {
            get {
                return ResourceManager.GetString("cbxBeta.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool cbxCodex_AutoSize {
            get {
                object obj = ResourceManager.GetObject("cbxCodex.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=34,Y=28}.
        /// </summary>
        public static System.Drawing.Point cbxCodex_Location {
            get {
                object obj = ResourceManager.GetObject("cbxCodex.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding cbxCodex_Margin {
            get {
                object obj = ResourceManager.GetObject("cbxCodex.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=178, Height=21}.
        /// </summary>
        public static System.Drawing.Size cbxCodex_Size {
            get {
                object obj = ResourceManager.GetObject("cbxCodex.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 20.
        /// </summary>
        public static int cbxCodex_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbxCodex.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descubrimientos Codex.
        /// </summary>
        public static string cbxCodex_Text {
            get {
                return ResourceManager.GetString("cbxCodex.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool cbxToast_AutoSize {
            get {
                object obj = ResourceManager.GetObject("cbxToast.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=315,Y=41}.
        /// </summary>
        public static System.Drawing.Point cbxToast_Location {
            get {
                object obj = ResourceManager.GetObject("cbxToast.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding cbxToast_Margin {
            get {
                object obj = ResourceManager.GetObject("cbxToast.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=170, Height=21}.
        /// </summary>
        public static System.Drawing.Size cbxToast_Size {
            get {
                object obj = ResourceManager.GetObject("cbxToast.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 8.
        /// </summary>
        public static int cbxToast_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbxToast.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Notificaciones.
        /// </summary>
        public static string cbxToast_Text {
            get {
                return ResourceManager.GetString("cbxToast.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool cbxTts_AutoSize {
            get {
                object obj = ResourceManager.GetObject("cbxTts.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=22,Y=95}.
        /// </summary>
        public static System.Drawing.Point cbxTts_Location {
            get {
                object obj = ResourceManager.GetObject("cbxTts.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding cbxTts_Margin {
            get {
                object obj = ResourceManager.GetObject("cbxTts.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=125, Height=21}.
        /// </summary>
        public static System.Drawing.Size cbxTts_Size {
            get {
                object obj = ResourceManager.GetObject("cbxTts.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 9.
        /// </summary>
        public static int cbxTts_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbxTts.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar Locutor.
        /// </summary>
        public static string cbxTts_Text {
            get {
                return ResourceManager.GetString("cbxTts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool checkBox1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("checkBox1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=38,Y=6}.
        /// </summary>
        public static System.Drawing.Point checkBox1_Location {
            get {
                object obj = ResourceManager.GetObject("checkBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=126, Height=21}.
        /// </summary>
        public static System.Drawing.Size checkBox1_Size {
            get {
                object obj = ResourceManager.GetObject("checkBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 28.
        /// </summary>
        public static int checkBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("checkBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Todos.
        /// </summary>
        public static string checkBox1_Text {
            get {
                return ResourceManager.GetString("checkBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool checkBoxTodos_AutoSize {
            get {
                object obj = ResourceManager.GetObject("checkBoxTodos.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=38,Y=6}.
        /// </summary>
        public static System.Drawing.Point checkBoxTodos_Location {
            get {
                object obj = ResourceManager.GetObject("checkBoxTodos.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=126, Height=21}.
        /// </summary>
        public static System.Drawing.Size checkBoxTodos_Size {
            get {
                object obj = ResourceManager.GetObject("checkBoxTodos.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 27.
        /// </summary>
        public static int checkBoxTodos_TabIndex {
            get {
                object obj = ResourceManager.GetObject("checkBoxTodos.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Todos.
        /// </summary>
        public static string checkBoxTodos_Text {
            get {
                return ResourceManager.GetString("checkBoxTodos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=17,Y=20}.
        /// </summary>
        public static System.Drawing.Point groupBox_misc_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox_misc.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding groupBox_misc_Margin {
            get {
                object obj = ResourceManager.GetObject("groupBox_misc.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding groupBox_misc_Padding {
            get {
                object obj = ResourceManager.GetObject("groupBox_misc.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=259, Height=61}.
        /// </summary>
        public static System.Drawing.Size groupBox_misc_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox_misc.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 1.
        /// </summary>
        public static int groupBox_misc_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox_misc.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diarios de Vuelo (Journal Logs).
        /// </summary>
        public static string groupBox_misc_Text {
            get {
                return ResourceManager.GetString("groupBox_misc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=34,Y=126}.
        /// </summary>
        public static System.Drawing.Point groupBox_TTS_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox_TTS.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding groupBox_TTS_Margin {
            get {
                object obj = ResourceManager.GetObject("groupBox_TTS.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding groupBox_TTS_Padding {
            get {
                object obj = ResourceManager.GetObject("groupBox_TTS.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=242, Height=85}.
        /// </summary>
        public static System.Drawing.Size groupBox_TTS_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox_TTS.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 2.
        /// </summary>
        public static int groupBox_TTS_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox_TTS.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        public static string groupBox_TTS_Text {
            get {
                return ResourceManager.GetString("groupBox_TTS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=327,Y=70}.
        /// </summary>
        public static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding groupBox1_Margin {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding groupBox1_Padding {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=242, Height=85}.
        /// </summary>
        public static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 3.
        /// </summary>
        public static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opacidad.
        /// </summary>
        public static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=592,Y=36}.
        /// </summary>
        public static System.Drawing.Point groupBox2_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding groupBox2_Margin {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding groupBox2_Padding {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=76, Height=119}.
        /// </summary>
        public static System.Drawing.Size groupBox2_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 11.
        /// </summary>
        public static int groupBox2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vertical.
        /// </summary>
        public static string groupBox2_Text {
            get {
                return ResourceManager.GetString("groupBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=31,Y=230}.
        /// </summary>
        public static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=53, Height=17}.
        /// </summary>
        public static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 13.
        /// </summary>
        public static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma:.
        /// </summary>
        public static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool lblPos_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblPos.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=546,Y=56}.
        /// </summary>
        public static System.Drawing.Point lblPos_Location {
            get {
                object obj = ResourceManager.GetObject("lblPos.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=46, Height=17}.
        /// </summary>
        public static System.Drawing.Size lblPos_Size {
            get {
                object obj = ResourceManager.GetObject("lblPos.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 24.
        /// </summary>
        public static int lblPos_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblPos.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a label1.
        /// </summary>
        public static string lblPos_Text {
            get {
                return ResourceManager.GetString("lblPos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=12,Y=12}.
        /// </summary>
        public static System.Drawing.Point TabControl_Location {
            get {
                object obj = ResourceManager.GetObject("TabControl.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=2,Right=3,Bottom=2}.
        /// </summary>
        public static System.Windows.Forms.Padding TabControl_Margin {
            get {
                object obj = ResourceManager.GetObject("TabControl.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=855, Height=409}.
        /// </summary>
        public static System.Drawing.Size TabControl_Size {
            get {
                object obj = ResourceManager.GetObject("TabControl.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 3.
        /// </summary>
        public static int TabControl_TabIndex {
            get {
                object obj = ResourceManager.GetObject("TabControl.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=4,Y=25}.
        /// </summary>
        public static System.Drawing.Point tabFSS_Location {
            get {
                object obj = ResourceManager.GetObject("tabFSS.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=3,Right=3,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding tabFSS_Padding {
            get {
                object obj = ResourceManager.GetObject("tabFSS.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=847, Height=380}.
        /// </summary>
        public static System.Drawing.Size tabFSS_Size {
            get {
                object obj = ResourceManager.GetObject("tabFSS.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 5.
        /// </summary>
        public static int tabFSS_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabFSS.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FSS.
        /// </summary>
        public static string tabFSS_Text {
            get {
                return ResourceManager.GetString("tabFSS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=4,Y=25}.
        /// </summary>
        public static System.Drawing.Point tabOculta_Location {
            get {
                object obj = ResourceManager.GetObject("tabOculta.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=2,Right=3,Bottom=2}.
        /// </summary>
        public static System.Windows.Forms.Padding tabOculta_Margin {
            get {
                object obj = ResourceManager.GetObject("tabOculta.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=2,Right=3,Bottom=2}.
        /// </summary>
        public static System.Windows.Forms.Padding tabOculta_Padding {
            get {
                object obj = ResourceManager.GetObject("tabOculta.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=847, Height=380}.
        /// </summary>
        public static System.Drawing.Size tabOculta_Size {
            get {
                object obj = ResourceManager.GetObject("tabOculta.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 0.
        /// </summary>
        public static int tabOculta_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabOculta.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exploración (old).
        /// </summary>
        public static string tabOculta_Text {
            get {
                return ResourceManager.GetString("tabOculta.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=4,Y=25}.
        /// </summary>
        public static System.Drawing.Point tabPage3_Location {
            get {
                object obj = ResourceManager.GetObject("tabPage3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=2,Right=3,Bottom=2}.
        /// </summary>
        public static System.Windows.Forms.Padding tabPage3_Margin {
            get {
                object obj = ResourceManager.GetObject("tabPage3.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=2,Right=3,Bottom=2}.
        /// </summary>
        public static System.Windows.Forms.Padding tabPage3_Padding {
            get {
                object obj = ResourceManager.GetObject("tabPage3.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=847, Height=380}.
        /// </summary>
        public static System.Drawing.Size tabPage3_Size {
            get {
                object obj = ResourceManager.GetObject("tabPage3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 2.
        /// </summary>
        public static int tabPage3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabPage3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Varios.
        /// </summary>
        public static string tabPage3_Text {
            get {
                return ResourceManager.GetString("tabPage3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool tabScan_AutoScroll {
            get {
                object obj = ResourceManager.GetObject("tabScan.AutoScroll", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.ImeMode similar a Disable.
        /// </summary>
        public static System.Windows.Forms.ImeMode tabScan_ImeMode {
            get {
                object obj = ResourceManager.GetObject("tabScan.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=4,Y=25}.
        /// </summary>
        public static System.Drawing.Point tabScan_Location {
            get {
                object obj = ResourceManager.GetObject("tabScan.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=3,Right=3,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding tabScan_Padding {
            get {
                object obj = ResourceManager.GetObject("tabScan.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=847, Height=380}.
        /// </summary>
        public static System.Drawing.Size tabScan_Size {
            get {
                object obj = ResourceManager.GetObject("tabScan.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 3.
        /// </summary>
        public static int tabScan_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabScan.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exploración.
        /// </summary>
        public static string tabScan_Text {
            get {
                return ResourceManager.GetString("tabScan.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool tabSignal_AutoScroll {
            get {
                object obj = ResourceManager.GetObject("tabSignal.AutoScroll", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=4,Y=25}.
        /// </summary>
        public static System.Drawing.Point tabSignal_Location {
            get {
                object obj = ResourceManager.GetObject("tabSignal.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=3,Top=3,Right=3,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding tabSignal_Padding {
            get {
                object obj = ResourceManager.GetObject("tabSignal.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=847, Height=380}.
        /// </summary>
        public static System.Drawing.Size tabSignal_Size {
            get {
                object obj = ResourceManager.GetObject("tabSignal.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 4.
        /// </summary>
        public static int tabSignal_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabSignal.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Señales.
        /// </summary>
        public static string tabSignal_Text {
            get {
                return ResourceManager.GetString("tabSignal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point tipCopy_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tipCopy.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=13,Y=19}.
        /// </summary>
        public static System.Drawing.Point trackAlto_Location {
            get {
                object obj = ResourceManager.GetObject("trackAlto.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding trackAlto_Margin {
            get {
                object obj = ResourceManager.GetObject("trackAlto.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Orientation similar a Vertical.
        /// </summary>
        public static System.Windows.Forms.Orientation trackAlto_Orientation {
            get {
                object obj = ResourceManager.GetObject("trackAlto.Orientation", resourceCulture);
                return ((System.Windows.Forms.Orientation)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=56, Height=95}.
        /// </summary>
        public static System.Drawing.Size trackAlto_Size {
            get {
                object obj = ResourceManager.GetObject("trackAlto.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 10.
        /// </summary>
        public static int trackAlto_TabIndex {
            get {
                object obj = ResourceManager.GetObject("trackAlto.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=22,Y=23}.
        /// </summary>
        public static System.Drawing.Point trackBar_Transparencia_Location {
            get {
                object obj = ResourceManager.GetObject("trackBar_Transparencia.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding trackBar_Transparencia_Margin {
            get {
                object obj = ResourceManager.GetObject("trackBar_Transparencia.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=123, Height=56}.
        /// </summary>
        public static System.Drawing.Size trackBar_Transparencia_Size {
            get {
                object obj = ResourceManager.GetObject("trackBar_Transparencia.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 0.
        /// </summary>
        public static int trackBar_Transparencia_TabIndex {
            get {
                object obj = ResourceManager.GetObject("trackBar_Transparencia.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=11,Y=24}.
        /// </summary>
        public static System.Drawing.Point trackBar_Volume_Location {
            get {
                object obj = ResourceManager.GetObject("trackBar_Volume.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Windows.Forms.Padding similar a {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        public static System.Windows.Forms.Padding trackBar_Volume_Margin {
            get {
                object obj = ResourceManager.GetObject("trackBar_Volume.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Size similar a {Width=123, Height=56}.
        /// </summary>
        public static System.Drawing.Size trackBar_Volume_Size {
            get {
                object obj = ResourceManager.GetObject("trackBar_Volume.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 0.
        /// </summary>
        public static int trackBar_Volume_TabIndex {
            get {
                object obj = ResourceManager.GetObject("trackBar_Volume.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
